// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lcmd/lolaservice/lcmd.proto

package lolaservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpinUpRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// bool host_mount       = 2 [(wxio.dna.godna.help) = "mount /var/run into the container"];
	NxPort               int32    `protobuf:"varint,3,opt,name=nx_port,json=nxPort,proto3" json:"nx_port,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Username             string   `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	PasswdHash           string   `protobuf:"bytes,6,opt,name=passwd_hash,json=passwdHash,proto3" json:"passwd_hash,omitempty"`
	Gid                  int32    `protobuf:"varint,7,opt,name=gid,proto3" json:"gid,omitempty"`
	Uid                  int32    `protobuf:"varint,8,opt,name=uid,proto3" json:"uid,omitempty"`
	HomeBindPath         string   `protobuf:"bytes,9,opt,name=home_bind_path,json=homeBindPath,proto3" json:"home_bind_path,omitempty"`
	CapSysAdmin          bool     `protobuf:"varint,10,opt,name=cap_sys_admin,json=capSysAdmin,proto3" json:"cap_sys_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpinUpRequest) Reset()         { *m = SpinUpRequest{} }
func (m *SpinUpRequest) String() string { return proto.CompactTextString(m) }
func (*SpinUpRequest) ProtoMessage()    {}
func (*SpinUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_16441daed46e5584, []int{0}
}

func (m *SpinUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpinUpRequest.Unmarshal(m, b)
}
func (m *SpinUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpinUpRequest.Marshal(b, m, deterministic)
}
func (m *SpinUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpinUpRequest.Merge(m, src)
}
func (m *SpinUpRequest) XXX_Size() int {
	return xxx_messageInfo_SpinUpRequest.Size(m)
}
func (m *SpinUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpinUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpinUpRequest proto.InternalMessageInfo

func (m *SpinUpRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SpinUpRequest) GetNxPort() int32 {
	if m != nil {
		return m.NxPort
	}
	return 0
}

func (m *SpinUpRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *SpinUpRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SpinUpRequest) GetPasswdHash() string {
	if m != nil {
		return m.PasswdHash
	}
	return ""
}

func (m *SpinUpRequest) GetGid() int32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *SpinUpRequest) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SpinUpRequest) GetHomeBindPath() string {
	if m != nil {
		return m.HomeBindPath
	}
	return ""
}

func (m *SpinUpRequest) GetCapSysAdmin() bool {
	if m != nil {
		return m.CapSysAdmin
	}
	return false
}

type SpinUpResponse struct {
	Ports                *SpinUpResponse_PortMap `protobuf:"bytes,1,opt,name=ports,proto3" json:"ports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SpinUpResponse) Reset()         { *m = SpinUpResponse{} }
func (m *SpinUpResponse) String() string { return proto.CompactTextString(m) }
func (*SpinUpResponse) ProtoMessage()    {}
func (*SpinUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16441daed46e5584, []int{1}
}

func (m *SpinUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpinUpResponse.Unmarshal(m, b)
}
func (m *SpinUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpinUpResponse.Marshal(b, m, deterministic)
}
func (m *SpinUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpinUpResponse.Merge(m, src)
}
func (m *SpinUpResponse) XXX_Size() int {
	return xxx_messageInfo_SpinUpResponse.Size(m)
}
func (m *SpinUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpinUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpinUpResponse proto.InternalMessageInfo

func (m *SpinUpResponse) GetPorts() *SpinUpResponse_PortMap {
	if m != nil {
		return m.Ports
	}
	return nil
}

//
type SpinUpResponse_PortMap struct {
	Ports                map[string]*SpinUpResponse_Bindings `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *SpinUpResponse_PortMap) Reset()         { *m = SpinUpResponse_PortMap{} }
func (m *SpinUpResponse_PortMap) String() string { return proto.CompactTextString(m) }
func (*SpinUpResponse_PortMap) ProtoMessage()    {}
func (*SpinUpResponse_PortMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_16441daed46e5584, []int{1, 0}
}

func (m *SpinUpResponse_PortMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpinUpResponse_PortMap.Unmarshal(m, b)
}
func (m *SpinUpResponse_PortMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpinUpResponse_PortMap.Marshal(b, m, deterministic)
}
func (m *SpinUpResponse_PortMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpinUpResponse_PortMap.Merge(m, src)
}
func (m *SpinUpResponse_PortMap) XXX_Size() int {
	return xxx_messageInfo_SpinUpResponse_PortMap.Size(m)
}
func (m *SpinUpResponse_PortMap) XXX_DiscardUnknown() {
	xxx_messageInfo_SpinUpResponse_PortMap.DiscardUnknown(m)
}

var xxx_messageInfo_SpinUpResponse_PortMap proto.InternalMessageInfo

func (m *SpinUpResponse_PortMap) GetPorts() map[string]*SpinUpResponse_Bindings {
	if m != nil {
		return m.Ports
	}
	return nil
}

type SpinUpResponse_Bindings struct {
	Binding              []*SpinUpResponse_Bindings_Binding `protobuf:"bytes,1,rep,name=binding,proto3" json:"binding,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *SpinUpResponse_Bindings) Reset()         { *m = SpinUpResponse_Bindings{} }
func (m *SpinUpResponse_Bindings) String() string { return proto.CompactTextString(m) }
func (*SpinUpResponse_Bindings) ProtoMessage()    {}
func (*SpinUpResponse_Bindings) Descriptor() ([]byte, []int) {
	return fileDescriptor_16441daed46e5584, []int{1, 1}
}

func (m *SpinUpResponse_Bindings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpinUpResponse_Bindings.Unmarshal(m, b)
}
func (m *SpinUpResponse_Bindings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpinUpResponse_Bindings.Marshal(b, m, deterministic)
}
func (m *SpinUpResponse_Bindings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpinUpResponse_Bindings.Merge(m, src)
}
func (m *SpinUpResponse_Bindings) XXX_Size() int {
	return xxx_messageInfo_SpinUpResponse_Bindings.Size(m)
}
func (m *SpinUpResponse_Bindings) XXX_DiscardUnknown() {
	xxx_messageInfo_SpinUpResponse_Bindings.DiscardUnknown(m)
}

var xxx_messageInfo_SpinUpResponse_Bindings proto.InternalMessageInfo

func (m *SpinUpResponse_Bindings) GetBinding() []*SpinUpResponse_Bindings_Binding {
	if m != nil {
		return m.Binding
	}
	return nil
}

//
type SpinUpResponse_Bindings_Binding struct {
	HostIp               string   `protobuf:"bytes,1,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	HostPort             string   `protobuf:"bytes,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpinUpResponse_Bindings_Binding) Reset()         { *m = SpinUpResponse_Bindings_Binding{} }
func (m *SpinUpResponse_Bindings_Binding) String() string { return proto.CompactTextString(m) }
func (*SpinUpResponse_Bindings_Binding) ProtoMessage()    {}
func (*SpinUpResponse_Bindings_Binding) Descriptor() ([]byte, []int) {
	return fileDescriptor_16441daed46e5584, []int{1, 1, 0}
}

func (m *SpinUpResponse_Bindings_Binding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpinUpResponse_Bindings_Binding.Unmarshal(m, b)
}
func (m *SpinUpResponse_Bindings_Binding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpinUpResponse_Bindings_Binding.Marshal(b, m, deterministic)
}
func (m *SpinUpResponse_Bindings_Binding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpinUpResponse_Bindings_Binding.Merge(m, src)
}
func (m *SpinUpResponse_Bindings_Binding) XXX_Size() int {
	return xxx_messageInfo_SpinUpResponse_Bindings_Binding.Size(m)
}
func (m *SpinUpResponse_Bindings_Binding) XXX_DiscardUnknown() {
	xxx_messageInfo_SpinUpResponse_Bindings_Binding.DiscardUnknown(m)
}

var xxx_messageInfo_SpinUpResponse_Bindings_Binding proto.InternalMessageInfo

func (m *SpinUpResponse_Bindings_Binding) GetHostIp() string {
	if m != nil {
		return m.HostIp
	}
	return ""
}

func (m *SpinUpResponse_Bindings_Binding) GetHostPort() string {
	if m != nil {
		return m.HostPort
	}
	return ""
}

func init() {
	proto.RegisterType((*SpinUpRequest)(nil), "wxio.lmcd.SpinUpRequest")
	proto.RegisterType((*SpinUpResponse)(nil), "wxio.lmcd.SpinUpResponse")
	proto.RegisterType((*SpinUpResponse_PortMap)(nil), "wxio.lmcd.SpinUpResponse.PortMap")
	proto.RegisterMapType((map[string]*SpinUpResponse_Bindings)(nil), "wxio.lmcd.SpinUpResponse.PortMap.PortsEntry")
	proto.RegisterType((*SpinUpResponse_Bindings)(nil), "wxio.lmcd.SpinUpResponse.Bindings")
	proto.RegisterType((*SpinUpResponse_Bindings_Binding)(nil), "wxio.lmcd.SpinUpResponse.Bindings.Binding")
}

func init() { proto.RegisterFile("lcmd/lolaservice/lcmd.proto", fileDescriptor_16441daed46e5584) }

var fileDescriptor_16441daed46e5584 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x8b, 0xd4, 0x30,
	0x14, 0xc7, 0xed, 0xcc, 0xb4, 0x9d, 0x79, 0xe3, 0x2e, 0x12, 0x04, 0x63, 0xf7, 0xe0, 0x58, 0x3c,
	0x0c, 0x22, 0x1d, 0x18, 0x0f, 0x2e, 0x5e, 0x16, 0x07, 0x45, 0x05, 0x85, 0xa5, 0x8b, 0x17, 0x11,
	0x4a, 0xa6, 0x09, 0xd3, 0x60, 0x9b, 0xc4, 0x26, 0xdd, 0x9d, 0xfe, 0x0d, 0x9e, 0xfc, 0x3b, 0xfc,
	0x1b, 0x05, 0x49, 0xda, 0xee, 0xa2, 0xec, 0x32, 0xa7, 0xbe, 0x7c, 0xde, 0xcb, 0xf7, 0xfd, 0xe8,
	0x0b, 0x9c, 0x94, 0x79, 0x45, 0x57, 0xa5, 0x2c, 0x89, 0x66, 0xf5, 0x25, 0xcf, 0xd9, 0xca, 0x82,
	0x44, 0xd5, 0xd2, 0x48, 0x34, 0xbb, 0xda, 0x73, 0x99, 0x94, 0x55, 0x4e, 0xe3, 0x3f, 0x1e, 0x1c,
	0x5d, 0x28, 0x2e, 0xbe, 0xa8, 0x94, 0xfd, 0x68, 0x98, 0x36, 0x08, 0xc1, 0x44, 0x90, 0x8a, 0x61,
	0x6f, 0xe1, 0x2d, 0x67, 0xa9, 0xb3, 0xd1, 0x23, 0x08, 0xc5, 0x3e, 0x53, 0xb2, 0x36, 0x78, 0xbc,
	0xf0, 0x96, 0x7e, 0x1a, 0x88, 0xfd, 0xb9, 0xac, 0x0d, 0x7a, 0x08, 0x3e, 0xaf, 0xc8, 0x8e, 0xe1,
	0x89, 0x8b, 0xee, 0x0e, 0x28, 0x82, 0x69, 0xa3, 0x59, 0xed, 0x64, 0x7c, 0xe7, 0xb8, 0x3e, 0xa3,
	0x27, 0x30, 0x57, 0x44, 0xeb, 0x2b, 0x9a, 0x15, 0x44, 0x17, 0x38, 0x70, 0x6e, 0xe8, 0xd0, 0x07,
	0xa2, 0x0b, 0xf4, 0x00, 0xc6, 0x3b, 0x4e, 0x71, 0xe8, 0xf2, 0x58, 0xd3, 0x92, 0x86, 0x53, 0x3c,
	0xed, 0x48, 0xc3, 0x29, 0x7a, 0x06, 0xc7, 0x85, 0xac, 0x58, 0xb6, 0xe5, 0x82, 0x66, 0x8a, 0x98,
	0x02, 0xcf, 0x9c, 0xce, 0x7d, 0x4b, 0x37, 0x5c, 0xd0, 0x73, 0x62, 0x0a, 0x14, 0xc3, 0x51, 0x4e,
	0x54, 0xa6, 0x5b, 0x9d, 0x11, 0x5a, 0x71, 0x81, 0x61, 0xe1, 0x2d, 0xa7, 0xe9, 0x3c, 0x27, 0xea,
	0xa2, 0xd5, 0x6f, 0x2c, 0x8a, 0x7f, 0x8e, 0xe1, 0x78, 0xe8, 0x5f, 0x2b, 0x29, 0x34, 0x43, 0xaf,
	0xc0, 0xb7, 0x9d, 0x6a, 0x37, 0x81, 0xf9, 0xfa, 0x69, 0x72, 0x3d, 0xad, 0xe4, 0xdf, 0xc8, 0xc4,
	0x8e, 0xe0, 0x33, 0x51, 0x69, 0x17, 0x1f, 0xfd, 0xf6, 0x20, 0xec, 0x11, 0xda, 0xdc, 0x88, 0x8c,
	0x97, 0xf3, 0xf5, 0x8b, 0x83, 0x22, 0xee, 0xab, 0xdf, 0x09, 0x53, 0xb7, 0x83, 0xde, 0x37, 0x80,
	0x1b, 0x68, 0xa7, 0xf0, 0x9d, 0xb5, 0xfd, 0x6f, 0xb1, 0x26, 0x3a, 0x05, 0xff, 0x92, 0x94, 0x0d,
	0xc3, 0x23, 0x57, 0x68, 0x7c, 0x77, 0x0e, 0x3b, 0x12, 0x2e, 0x76, 0x3a, 0xed, 0x2e, 0xbc, 0x1e,
	0x9d, 0x7a, 0xd1, 0x2f, 0x0f, 0xa6, 0x03, 0x47, 0x6f, 0x21, 0xdc, 0x76, 0x76, 0x5f, 0xf0, 0xf3,
	0xc3, 0x62, 0x83, 0x91, 0x0e, 0x57, 0xa3, 0x33, 0x08, 0x7b, 0x66, 0x37, 0xa6, 0x90, 0xda, 0x64,
	0x5c, 0xf5, 0x15, 0x07, 0xf6, 0xf8, 0x51, 0xa1, 0x13, 0x98, 0x39, 0x87, 0x5b, 0xa6, 0x51, 0xb7,
	0x1c, 0x16, 0xd8, 0x4e, 0xd7, 0xef, 0x61, 0xf2, 0x49, 0x96, 0x04, 0x9d, 0x41, 0xd0, 0x25, 0x45,
	0xf8, 0x96, 0x3a, 0xdc, 0x9e, 0x46, 0x8f, 0xef, 0xac, 0x30, 0xbe, 0xb7, 0x89, 0xbf, 0x2e, 0x76,
	0xdc, 0x14, 0xcd, 0x36, 0xc9, 0x65, 0xb5, 0xb2, 0x81, 0xab, 0xff, 0x1f, 0xc4, 0x36, 0x70, 0x8f,
	0xe1, 0xe5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xa8, 0x38, 0x72, 0x2b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LolaClient is the client API for Lola service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LolaClient interface {
	SpinUp(ctx context.Context, in *SpinUpRequest, opts ...grpc.CallOption) (*SpinUpResponse, error)
}

type lolaClient struct {
	cc *grpc.ClientConn
}

func NewLolaClient(cc *grpc.ClientConn) LolaClient {
	return &lolaClient{cc}
}

func (c *lolaClient) SpinUp(ctx context.Context, in *SpinUpRequest, opts ...grpc.CallOption) (*SpinUpResponse, error) {
	out := new(SpinUpResponse)
	err := c.cc.Invoke(ctx, "/wxio.lmcd.Lola/SpinUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LolaServer is the server API for Lola service.
type LolaServer interface {
	SpinUp(context.Context, *SpinUpRequest) (*SpinUpResponse, error)
}

func RegisterLolaServer(s *grpc.Server, srv LolaServer) {
	s.RegisterService(&_Lola_serviceDesc, srv)
}

func _Lola_SpinUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpinUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LolaServer).SpinUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wxio.lmcd.Lola/SpinUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LolaServer).SpinUp(ctx, req.(*SpinUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lola_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wxio.lmcd.Lola",
	HandlerType: (*LolaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SpinUp",
			Handler:    _Lola_SpinUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lcmd/lolaservice/lcmd.proto",
}
